confirm_registration:
    path: /api/confirm_registration
    controller: App\Controller\AuthController::confirmRegistration
    methods: POST

reset_password:
    path: /api/reset_password
    controller: App\Controller\AuthController:resetPassword
    methods: POST

new_password:
    path: /api/new_password
    controller: App\Controller\AuthController:newPassword
    methods: POST

update_user:
    path: /api/user/update
    controller: App\Controller\UserController:updateUser
    methods: PUT

login_check:
    path: /api/login
    methods: POST
